pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-gcs
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: Google Cloud Storage
  desc: Publish files and artifacts to Google Cloud Storage
  type: publish
  image: plugins/drone-gcs
  labels:
    - publish
    - artifacts
    - google compute
